package com.datasalt.pangool.flow.ops;

import java.io.IOException;

import clojure.lang.Fn;

import com.datasalt.pangool.io.Fields;
import com.datasalt.pangool.io.ITuple;
import com.datasalt.pangool.io.Schema;

/**
 * Op to be used by the Clojure facade to Pangool-flow 
 * (Work-in-progress)
 */
@SuppressWarnings("serial")
public class ClojureOp<K> extends TupleOp<K> {

	Fn function;
	Schema pangoolSchema;
	
	public ClojureOp(Fn function, String schema) {
		super(new Schema("autogenerated", Fields.parse(schema)));
		this.function = function;		
	}

	@Override
  public void process(K input, ReturnCallback<ITuple> callback) throws IOException, InterruptedException {
	  // TODO: Actually do something here
  }
}
